# Generated by Django 4.2.16 on 2024-12-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevel',
            name='multiplier',
            field=models.FloatField(default=0),
        ),
    ]
