# Generated by Django 4.2.16 on 2024-12-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0002_activitylevel_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevel',
            name='multiplier',
            field=models.FloatField(),
        ),
    ]
