# Generated by Django 4.2.16 on 2024-12-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0003_alter_activitylevel_multiplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietplan',
            options={'ordering': ['goal', 'calorie_range_min'], 'verbose_name': 'Diet Plan', 'verbose_name_plural': 'Diet Plans'},
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='user_info',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='breakfast',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='calorie_range_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='calorie_range_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='carbs_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='dinner',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='fat_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='lunch',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='protein_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='snacks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplan.dietgoal'),
        ),
    ]
