# Generated by Django 4.2.16 on 2024-12-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0004_alter_dietplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='snacks2',
            field=models.TextField(default=''),
        ),
    ]
