# Generated by Django 4.2.16 on 2024-12-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0005_dietplan_snacks2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='snacks3',
            field=models.TextField(default=''),
        ),
    ]
