# Generated by Django 4.2.16 on 2024-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0006_dietplan_snacks3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='snacks3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
